### ISSUE TITLE
Exception during octopus parsing

### ISSUE THREAD

**Issue by markus1978** [nomad-coe/electronic-parsers#1]
This was reported by a user:

I just tried to upload an Octopus calculation and it seems that the Octopus parser is broken.

The upload ID is the following:
sUu9KlKGSZ-YHEjxuHWqug

The logs show a problem of the parser:
 Traceback (most recent call last):
  File "/app/nomad/processing/data.py", line 466, in parsing
    self._parser_results, logger=logger)
  File "/usr/local/lib/python3.7/site-packages/octopusparser/octopus_parser.py", line 910, in parse
    self.parse_system()
  File "/usr/local/lib/python3.7/site-packages/octopusparser/octopus_parser.py", line 798, in parse_system
    sec_system.atom_positions = coordinates * self._units_mapping.get(units.lower())
AttributeError: 'Unit' object has no attribute 'lower'

**Comment by markus1978** [comment]
@ladinesa could you have a look?

**Comment by ladinesa** [comment]
This has already been fixed.
