### ISSUE TITLE
CP2K parser failing at PROCESS ID

### ISSUE THREAD

**Issue by ndaelman-hu** [nomad-coe/electronic-parsers#242]
A user complained of failing CP2K parser with the following error log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nomad/processing/data.py", line 1507, in parsing
    parser.parse(
  File "/usr/local/lib/python3.11/site-packages/nomad/parsing/parser.py", line 463, in parse
    self.mainfile_parser.parse(mainfile, archive, logger)
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/cp2k/parser.py", line 2288, in parse
    self.parse_settings()
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/cp2k/parser.py", line 1492, in parse_settings
    section.m_set(section.m_get_quantity_definition(f'x_cp2k_{key}'), val)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nomad/metainfo/metainfo.py", line 1284, in m_get_quantity_definition
    return resolve_variadic_name(self.m_def.all_quantities, quantity_name, hint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nomad/metainfo/util.py", line 359, in resolve_variadic_name
    raise ValueError(f'Cannot find a proper definition for name {name}')
ValueError: Cannot find a proper definition for name x_cp2k_id
```

**Comment by ndaelman-hu** [comment]
I traced back the issue to the parsing of `PROGRAM PROCESS ID <int>`. This line appears twice, once at the start and once at the end of the calculation. Both lines are parsed to the `program_settings[id] = [<start_proc_id>, <end_proc_id>]`. These are mapped to `x_cp2k_section_start_information().x_cp2k_start_id` and `x_cp2k_section_end_information().x_cp2k_end_id`, respectively, by manipulating the key name.

However, if a calculation terminates improperly, not producing the end section, `id` is retained and an invalid quantity name generated. I will fix this by capturing the both scenarios and clarifying the key name to `process_id` for easier mapping to the output file.
The schema could furthermore be simplified to using `x_cp2k_id` quantities in both sections. Given that it is to be depricated and would break with older schemas, this will not be modified here.
