### ISSUE TITLE
VASP parser regression: ValueError('Cannot normalize HDF5 value without context.')

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/electronic-parsers#245]
testcase: [single_point.zip](https://github.com/user-attachments/files/16845570/single_point.zip)

I assume this is related to cases with charge density (uploading just the vasprun.xml works fine) and this case this specific case was parsed fine in the NOMAD in the past (it doesn't parse neither with the stable nor staging servers now, but it worked during the latest mass reprocessing)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nomad/processing/data.py", line 1507, in parsing
    parser.parse(
  File "/usr/local/lib/python3.11/site-packages/nomad/parsing/parser.py", line 463, in parse
    self.mainfile_parser.parse(mainfile, archive, logger)
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 2336, in parse
    self.parse_configurations()
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 2274, in parse_configurations
    sec_density.value_hdf5 = np.reshape(
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nomad/metainfo/metainfo.py", line 1083, in __setattr__
    return super().__setattr__(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nomad/metainfo/metainfo.py", line 3325, in __set__
    obj.m_set(self, value)
  File "/usr/local/lib/python3.11/site-packages/nomad/metainfo/metainfo.py", line 1208, in m_set
    value = quantity_def.type.normalize(value, section=self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nomad/metainfo/data_type.py", line 726, in normalize
    return self._normalize_impl(value, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nomad/datamodel/hdf5.py", line 118, in _normalize_impl
    raise ValueError('Cannot normalize HDF5 value without context.')
ValueError: Cannot normalize HDF5 value without context.
```

Might be related to https://github.com/nomad-coe/electronic-parsers/pull/214 so cc @ladinesa

**Comment by ladinesa** [comment]
@TLCFEM this is kind of strange that the archive does not have a context.

**Comment by TLCFEM** [comment]
Do this:

```
                    sec_density = Density()
                    sec_scc.density_charge.append(sec_density)
                    sec_density.value_hdf5 = np.reshape(
                        np.array(charge_density, np.float64), grid
                    )
```

**Comment by ondracka** [comment]
Thanks a lot for the quick fix.
