### ISSUE TITLE
VASP parser regression: integer division or modulo by zero in n_eigs = len(eigenvalues) // (self.ispin * n_kpts)

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/electronic-parsers#246]
Another VASP issue I hit during local mass reprocessing with 1.3.6. Used to work in the past as well.

testcase: [OUTCAR.zip](https://github.com/user-attachments/files/16845718/OUTCAR.zip)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nomad/processing/data.py", line 1507, in parsing
    parser.parse(
  File "/usr/local/lib/python3.11/site-packages/nomad/parsing/parser.py", line 463, in parse
    self.mainfile_parser.parse(mainfile, archive, logger)
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 2336, in parse
    self.parse_configurations()
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 2242, in parse_configurations
    parse_eigenvalues(n)
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 2044, in parse_eigenvalues
    eigenvalues = self.parser.get_eigenvalues(n_calc)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 876, in get_eigenvalues
    n_eigs = len(eigenvalues) // (self.ispin * n_kpts)
             ~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: integer division or modulo by zero
```

**Comment by ondracka** [comment]
Sorry, this one is actually a duplicate of https://github.com/nomad-coe/electronic-parsers/issues/209
