### ISSUE TITLE
Quantum ESPRESSO parser fails when parsing reciprocal cell

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/electronic-parsers#75]
Noticed this failure in an Oasis and unfortunately I was not able to figure this out on my own.
Test file: [pw.zip](https://github.com/nomad-coe/electronic-parsers/files/11110954/pw.zip)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nomad/processing/data.py", line 1155, in parsing
    parser.parse(self.mainfile_file.os_path, self._parser_results, logger=logger, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nomad/parsing/parser.py", line 394, in parse
    self.mainfile_parser.parse(mainfile, archive, logger)
  File "/usr/local/lib/python3.7/site-packages/electronicparsers/quantumespresso/parser.py", line 2752, in parse
    self.parse_configurations(run)
  File "/usr/local/lib/python3.7/site-packages/electronicparsers/quantumespresso/parser.py", line 2493, in parse_configurations
    parse_configuration(calculation)
  File "/usr/local/lib/python3.7/site-packages/electronicparsers/quantumespresso/parser.py", line 2466, in parse_configuration
    sec_system = self.parse_system(run, calculation)
  File "/usr/local/lib/python3.7/site-packages/electronicparsers/quantumespresso/parser.py", line 2387, in parse_system
    reciprocal_cell = _convert('reciprocal_cell', calculation, 'reciprocal_cell_units')
  File "/usr/local/lib/python3.7/site-packages/electronicparsers/quantumespresso/parser.py", line 2345, in _convert
    units = units.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by JosePizarro3** [comment]
I wonder whether this is a similar case to #76 . Did you test the data on the NOMAD beta? :slightly_smiling_face:

**Comment by ondracka** [comment]
No, this one happens also with the upstream staging server (and I can also reproduce it locally with command line running the latest develop branch of nomad and electronic-parsers).
