### ISSUE TITLE
Wannier90 parsing fails with "cannot reshape array of size 29554875 into shape (2085,16,7)" in parse_hoppings

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/electronic-parsers#76]
Another failure seen after Oasis update.

Testcase: [Ti3AlC2-wout.zip](https://github.com/nomad-coe/electronic-parsers/files/11111253/Ti3AlC2-wout.zip)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nomad/processing/data.py", line 1155, in parsing
    parser.parse(self.mainfile_file.os_path, self._parser_results, logger=logger, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nomad/parsing/parser.py", line 394, in parse
    self.mainfile_parser.parse(mainfile, archive, logger)
  File "/usr/local/lib/python3.7/site-packages/electronicparsers/wannier90/parser.py", line 362, in parse
    self.parse_scc()
  File "/usr/local/lib/python3.7/site-packages/electronicparsers/wannier90/parser.py", line 329, in parse_scc
    self.parse_hoppings()
  File "/usr/local/lib/python3.7/site-packages/electronicparsers/wannier90/parser.py", line 196, in parse_hoppings
    full_hoppings, (sec_hopping_matrix.n_wigner_seitz_points, sec_hopping_matrix.n_orbitals * sec_hopping_matrix.n_orbitals, 7))
  File "<__array_function__ internals>", line 6, in reshape
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 29554875 into shape (2085,16,7)
```

**Comment by JosePizarro3** [comment]
Hi @ondracka ,

Thanks for pointing this out. I cannot reproduce this issue in the NOMAD beta version, as I have patched it.

I am always scared that the NOMAD Oasis version will get behind of the current developments very quickly w.r.t. the central NOMAD, specially for computations. This is the case here.

May I ask what is the purpose of your NOMAD Oasis? This is an involved question that also requires that we sit with @ladinesa and @ndaelman-hu , as I am not a big fan of computational users installing an Oasis but rather contacting and developing in the central (as you are very well doing). Do you have some experimental data in there? I seem to recall that you were indeed on charge of this kind of data in your department.

I am sorry I don't have a more satisfactory answer. Maybe @markus1978 can shed more light on this.

**Comment by ondracka** [comment]
Sorry, I'm closing this than, I tested with the upstream production and the oasis (which is running with the gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair:latest image, so I was assuming this should be based on the develop branch, but maybe its not so bleeding edge). I confirm this is fixed with the staging nomad, so it will eventually come to the Oasis as well...
